# Generated by Django 5.0.1 on 2024-02-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='idempresa',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
