# Generated by Django 5.0.1 on 2024-02-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipoenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoenvio',
            name='tipo_envio',
            field=models.CharField(max_length=1),
        ),
    ]
