# Generated by Django 5.0.1 on 2024-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tipoenvio_tipo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoenvio',
            name='tipo_envio',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
