# Generated by Django 5.0.1 on 2024-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tipoenvio_tipo_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('idresponsable', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=255)),
            ],
        ),
    ]
