# Generated by Django 5.0.1 on 2024-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_responsable_nombre_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='idresponsable',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
