# Generated by Django 5.0.1 on 2024-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_responsable_idresponsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idplanilla', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
