# Generated by Django 5.0.1 on 2024-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_importarasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistencia',
            name='cantidad',
            field=models.CharField(max_length=255),
        ),
    ]
