# Generated by Django 5.0.1 on 2024-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_importarasistencia_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistencia',
            name='cantidad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='fecha',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idempresa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idlabor',
            field=models.CharField(max_length=6),
        ),
    ]
