# Generated by Django 5.0.1 on 2024-02-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_importarasistencia_idempresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportarAsistencia',
        ),
    ]
