# Generated by Django 5.0.1 on 2024-02-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_importarasistencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportarAsistencia',
        ),
    ]
