# Generated by Django 5.0.1 on 2024-02-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_importarasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistencia',
            name='idactividad',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idcodigogeneral',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idconsumidor',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idemisor',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idespecie',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idlabor',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idplanilla',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idresponsable',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idsucursal',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='idturno',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='item',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='tipo_envio',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
