# Generated by Django 5.0.1 on 2024-02-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='fecha_hora_cierre',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
