# Generated by Django 5.0.1 on 2024-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_importarasistencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
