# Generated by Django 5.0.1 on 2024-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_importarasistencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='fecha_hora_cierre',
        ),
        migrations.AlterField(
            model_name='importarasistencia',
            name='fecha',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
