# Generated by Django 5.0.1 on 2024-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_especie_delete_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('abierto', models.BooleanField(default=False)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
