# Generated by Django 5.0.1 on 2024-02-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_estadodia_delete_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportarAsistencia',
        ),
    ]
